### ISSUE TITLE
Error when triggering particle after communications update

### ISSUE THREAD

**Issue by BastiaanVeldhuisen** [THDigi/ParticleEditor#3]
Hi Digi,

As of the communications update I'm getting a crash to desktop when triggering a particle with F or when switching from loaded particles.  I don't know if it has something to do with the pluginloader not being compatible or not, but anyways I've attached the entire log (it closes on the error). 
[SpaceEngineers_20240518_233228137.log](https://github.com/THDigi/ParticleEditor/files/15366912/SpaceEngineers_20240518_233228137.log)
Hope you're able to look into this and I really appreciate what you're doing.

Kind regards,
Gaz

**Comment by THDigi** [comment]
Yep found it, they're nulling something when a non-looping effect finishes, thanks! Will be fixed soon enough.

**Comment by BastiaanVeldhuisen** [comment]
Nice! Thank you.

**Comment by BastiaanVeldhuisen** [comment]
Hi Digi,

I noticed the same error still persisting after the issue was completed in version 1.05. I've let the plugin get patched and restarted the plugin loader, but it still ctd's when in any way a specific particle triggers two times in a row. Not sure if you're still looking at it, but in any case thought I'd let you know.

Kind regards,
Gaz

**Comment by THDigi** [comment]
1.06 is the version that has this fixed, check top-right in the UI for the version to ensure you have that.

If you do have the latest and still crashes, can you post the new crashlog.

**Comment by BastiaanVeldhuisen** [comment]
Ah, I can't seem to install 1.06, it's not in the plugin list when pressing add plugin. Is there an alternative way to update it?

**Comment by THDigi** [comment]
Ops! I made a PR on my fork instead of the actual pluginhub =) it's submitted now, should be updated when they finish checking stuff.

You can see when it's merged here: https://github.com/sepluginloader/PluginHub/pull/308
